// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Product struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Links     []string       `json:"links"`
	Price     sql.NullString `json:"price"`
	CreatedAt time.Time      `json:"created_at"`
}

type ProductsCategory struct {
	ShopID sql.NullInt32  `json:"shop_id"`
	ID     int32          `json:"id"`
	Name   string         `json:"name"`
	Link   sql.NullString `json:"link"`
}

type ProductsProductsCategory struct {
	ProductCategoryID sql.NullInt32 `json:"product_category_id"`
	ProductID         sql.NullInt32 `json:"product_id"`
}

type Shop struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Link      sql.NullString `json:"link"`
	CreatedAt time.Time      `json:"created_at"`
}

type ShopsCategory struct {
	ID   int32          `json:"id"`
	Name string         `json:"name"`
	Link sql.NullString `json:"link"`
}

type ShopsShopsCategory struct {
	ShopCategoryID sql.NullInt32 `json:"shop_category_id"`
	ShopID         sql.NullInt32 `json:"shop_id"`
}
