// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Product struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Links     []string  `json:"links"`
	Price     string    `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}

type ProductsCategory struct {
	ShopID int32  `json:"shop_id"`
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Link   string `json:"link"`
}

type ProductsProductsCategory struct {
	ProductCategoryID int32 `json:"product_category_id"`
	ProductID         int32 `json:"product_id"`
}

type Shop struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Link      string    `json:"link"`
	CreatedAt time.Time `json:"created_at"`
}

type ShopsCategory struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Link string `json:"link"`
}

type ShopsShopsCategory struct {
	ShopCategoryID sql.NullInt32 `json:"shop_category_id"`
	ShopID         sql.NullInt32 `json:"shop_id"`
}
