// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	CreateShopCategory(ctx context.Context, arg CreateShopCategoryParams) (ShopsCategory, error)
	GetShop(ctx context.Context, id int32) (Shop, error)
	GetShopCategory(ctx context.Context, id int32) (ShopsCategory, error)
	ListShops(ctx context.Context, arg ListShopsParams) ([]Shop, error)
	ListShopsCategories(ctx context.Context, arg ListShopsCategoriesParams) ([]ShopsCategory, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
	UpdateShopCategory(ctx context.Context, arg UpdateShopCategoryParams) (ShopsCategory, error)
}

var _ Querier = (*Queries)(nil)
